[package]
name = "embedded-hal-async-mocks"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-hal-async = "1.0.0-rc.3"
futures = { version = "0.3", default-features = false }
mockall = "0.11"
